### ISSUE TITLE
Blogs crossposting

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/cargomedia.github.io#136]
I would suggest to crosspost + maybe some tuning:
- [x] [simple video chat](http://blog.kris-lab.com/simple-osx-bi-directional-video-chat-using-ffmpeg-ffplay-and-wowza/) via #138 
- [x] [PULSAR REST API](http://blog.kris-lab.com/pulsar-rest-api/) via #137 
- [x] [simple streaming ffmpeg/wowza workflow](http://blog.kris-lab.com/video-streaming-benchmark-with-ffmpeg-ffserver-wowza/) via #139 
- [x] [wowza on aws with gpu](http://blog.kris-lab.com/wowza-powered-by-m3-and-g2-instances-on-aws/) via #140 

@njam wdyt?

**Comment by njam** [comment]
Not sure how much work it is. Do you you Markdown?
If you want less work I would go with post 2 and 3.

**Comment by kris-lab** [comment]
It is not too much work. There is no really markdown (some wordpress styling) but it is easy to migrate.

I can migrate all of them!

**Comment by fabianfrey** [comment]
Would be cool, to have all of them!

**Comment by kris-lab** [comment]
All has been done for now.
